### ISSUE TITLE
Weird internal cast exception

### ISSUE THREAD

**Issue by zekronium** [vsilaev/tascalate-async-await#13]
```
[23:03:35.709]|ERROR|StackRecorder| > class net.tascalate.async.core.AsyncMethodExecutor cannot be cast to class net.tascalate.async.core.AsyncTaskMethod (net.tascalate.async.core.AsyncMethodExecutor and net.tascalate.async.core.AsyncTaskMethod are in unnamed module of loader 'app')
java.lang.ClassCastException: class net.tascalate.async.core.AsyncMethodExecutor cannot be cast to class net.tascalate.async.core.AsyncTaskMethod (net.tascalate.async.core.AsyncMethodExecutor and net.tascalate.async.core.AsyncTaskMethod are in unnamed module of loader 'app')
	at net.tascalate.async.core.AsyncTaskMethod.internalRun(AsyncTaskMethod.java)
	at net.tascalate.async.core.AbstractAsyncMethod.run(AbstractAsyncMethod.java:66)
	at org.apache.commons.javaflow.core.StackRecorder.execute(StackRecorder.java:122)
	at org.apache.commons.javaflow.api.Continuation$SingleShotContinuation.resumeWith(Continuation.java:573)
	at org.apache.commons.javaflow.api.Continuation.resume(Continuation.java:314)
	at net.tascalate.async.core.AsyncMethodExecutor.resume(AsyncMethodExecutor.java:76)
	at net.tascalate.async.core.AsyncMethodExecutor$ContinuationResumer.run(AsyncMethodExecutor.java:260)
	at net.tascalate.async.scheduler.SimpleScheduler$2.run(SimpleScheduler.java:65)
	at net.tascalate.async.scheduler.SimpleScheduler.schedule(SimpleScheduler.java:72)
	at net.tascalate.async.core.AbstractAsyncMethod$2.run(AbstractAsyncMethod.java:144)
	at net.tascalate.async.core.AsyncMethodExecutor.lambda$setupContinuation$0(AsyncMethodExecutor.java:109)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
```

**Comment by zekronium** [comment]
This occurs when running tests.

What is the correct way to execute Junit tests?

**Comment by vsilaev** [comment]
Typically this means that code enhancement plugins was not executed (most probably JavaFlow due to wrong object on stack). For tests plugins must be configured for 'process-test-classes' phase, in addition to 'process-classes'
